import { useState } from 'react';
import { motion } from 'framer-motion';
import jsPDF from 'jspdf';
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  RadarChart,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  Radar,
  Legend,
} from 'recharts';
import { useGameStore } from '../store/gameStore';
import { formatNumber, getEventEmoji } from '../utils/gameUtils';

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.08 },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { type: 'spring', stiffness: 100 },
  },
};

const getHeatColor = (visits: number, maxVisits: number) => {
  const ratio = visits / maxVisits;
  if (ratio >= 0.8) return '#C9A227';
  if (ratio >= 0.5) return '#1E5AA8';
  if (ratio >= 0.25) return '#2A5A8C';
  return '#3A7CA5';
};

export default function Logbook() {
  const { weeklyLog, player } = useGameStore();
  const [selectedWeek, setSelectedWeek] = useState('本周');
  const [hoveredRoute, setHoveredRoute] = useState<string | null>(null);

  const weeks = ['本周', '上周', '两周前', '三周前'];

  const handleExportPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.setTextColor(201, 162, 39);
    doc.text("Captain's Log - Weekly Report", 20, 25);

    doc.setFontSize(12);
    doc.setTextColor(60, 60, 60);
    doc.text(`Period: ${weeklyLog.weekStart} - ${weeklyLog.weekEnd}`, 20, 40);
    doc.text(`Captain: ${player.name}`, 20, 50);

    doc.setFontSize(14);
    doc.setTextColor(201, 162, 39);
    doc.text('Weekly Summary', 20, 70);

    doc.setFontSize(11);
    doc.setTextColor(60, 60, 60);
    doc.text(`Voyages: ${weeklyLog.voyageCount}`, 25, 82);
    doc.text(`Battles Won: ${weeklyLog.battleWins}`, 25, 92);
    doc.text(`Battles Lost: ${weeklyLog.battleLosses}`, 25, 102);
    doc.text(`Gold Earned: ${formatNumber(weeklyLog.totalGoldEarned)}`, 25, 112);
    doc.text(`Gold Spent: ${formatNumber(weeklyLog.totalGoldSpent)}`, 25, 122);
    doc.text(`Ships Sunk: ${weeklyLog.battleStats.shipsSunk}`, 25, 132);
    doc.text(`Cannons Fired: ${weeklyLog.battleStats.cannonsFired}`, 25, 142);
    doc.text(`Damage Dealt: ${formatNumber(weeklyLog.battleStats.damageDealt)}`, 25, 152);
    doc.text(`Damage Taken: ${formatNumber(weeklyLog.battleStats.damageTaken)}`, 25, 162);

    doc.setFontSize(10);
    doc.setTextColor(120, 120, 120);
    doc.text('Generated by Pirate Captain Log System', 20, 280);

    doc.save(`captains-log-${weeklyLog.weekStart}.pdf`);
  };

  const maxVisits = Math.max(...weeklyLog.routes.map((r) => r.visits), 1);

  const radarData = [
    { dimension: '击沉数', value: weeklyLog.battleStats.shipsSunk, fullMark: 20 },
    { dimension: '开火数', value: Math.min(weeklyLog.battleStats.cannonsFired / 20, 100), fullMark: 100 },
    { dimension: '伤害输出', value: Math.min(weeklyLog.battleStats.damageDealt / 100, 100), fullMark: 100 },
    { dimension: '伤害承受', value: Math.min(weeklyLog.battleStats.damageTaken / 50, 100), fullMark: 100 },
    { dimension: '损失船员', value: weeklyLog.battleStats.crewLost * 10, fullMark: 100 },
    { dimension: '招募船员', value: weeklyLog.battleStats.crewRecruited * 10, fullMark: 100 },
  ];

  const statCards = [
    {
      label: '航行次数',
      value: weeklyLog.voyageCount,
      icon: '🧭',
      color: 'from-ocean-400 to-ocean-600',
    },
    {
      label: '战斗胜/败',
      value: `${weeklyLog.battleWins}/${weeklyLog.battleLosses}`,
      icon: '⚔️',
      color: 'from-blood-400 to-blood-600',
    },
    {
      label: '收入/支出',
      value: `${formatNumber(weeklyLog.totalGoldEarned)}/${formatNumber(weeklyLog.totalGoldSpent)}`,
      icon: '💰',
      color: 'from-gold-400 to-gold-600',
    },
    {
      label: '击沉敌舰',
      value: weeklyLog.battleStats.shipsSunk,
      icon: '💀',
      color: 'from-copper-500 to-copper-700',
    },
  ];

  const sortedEvents = [...weeklyLog.events].sort((a, b) => b.timestamp - a.timestamp);

  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="min-h-screen p-4 md:p-8"
    >
      <motion.div variants={itemVariants} className="pirate-card p-6 mb-6">
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
          <div>
            <h1 className="heading-display text-3xl text-gold-300 mb-2 flex items-center gap-2">
              <span>📜</span> 船长日志
            </h1>
            <p className="text-parchment-300 text-sm">
              {weeklyLog.weekStart} ~ {weeklyLog.weekEnd}
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-3">
            <div className="flex bg-ocean-700/60 rounded-lg border border-gold-500/40 overflow-hidden">
              {weeks.map((week) => (
                <button
                  key={week}
                  onClick={() => setSelectedWeek(week)}
                  className={`px-4 py-2 font-display text-sm transition-all ${
                    selectedWeek === week
                      ? 'bg-gold-500/30 text-gold-200'
                      : 'text-parchment-300 hover:bg-ocean-600/50'
                  }`}
                >
                  {week}
                </button>
              ))}
            </div>
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={handleExportPDF}
              className="pirate-btn-gold"
            >
              📄 导出PDF报告
            </motion.button>
          </div>
        </div>
      </motion.div>

      <motion.div variants={itemVariants} className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        {statCards.map((card) => (
          <motion.div
            key={card.label}
            whileHover={{ scale: 1.03, y: -4 }}
            className={`pirate-card p-5 bg-gradient-to-br ${card.color}`}
          >
            <div className="text-4xl mb-2">{card.icon}</div>
            <div className="font-display font-bold text-gold-100 text-2xl mb-1">
              {card.value}
            </div>
            <div className="text-parchment-200 text-sm">{card.label}</div>
          </motion.div>
        ))}
      </motion.div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
        <motion.div variants={itemVariants} className="pirate-card p-6">
          <h2 className="heading-display text-xl text-gold-300 mb-4 flex items-center gap-2">
            <span>🗺️</span> 航线热力图
          </h2>
          <div className="relative rounded-lg overflow-hidden bg-ocean-800/50 border border-gold-500/30">
            <svg viewBox="0 0 1000 600" className="w-full h-auto">
              <defs>
                <pattern id="grid" width="50" height="50" patternUnits="userSpaceOnUse">
                  <path
                    d="M 50 0 L 0 0 0 50"
                    fill="none"
                    stroke="rgba(201, 162, 39, 0.1)"
                    strokeWidth="1"
                  />
                </pattern>
                <radialGradient id="oceanGrad" cx="50%" cy="50%" r="70%">
                  <stop offset="0%" stopColor="#1E5AA8" stopOpacity="0.6" />
                  <stop offset="100%" stopColor="#0A2342" stopOpacity="0.9" />
                </radialGradient>
              </defs>
              <rect width="1000" height="600" fill="url(#oceanGrad)" />
              <rect width="1000" height="600" fill="url(#grid)" />
              <path
                d="M 100 300 Q 200 200 350 280 T 600 300 T 900 250 L 900 500 Q 700 550 500 500 T 100 480 Z"
                fill="#5C4033"
                fillOpacity="0.4"
                stroke="#C9A227"
                strokeWidth="2"
                strokeOpacity="0.5"
              />
              <path
                d="M 150 150 Q 300 100 450 180 T 750 150 L 750 200 Q 550 250 350 220 T 150 200 Z"
                fill="#5C4033"
                fillOpacity="0.3"
                stroke="#C9A227"
                strokeWidth="1.5"
                strokeOpacity="0.4"
              />
              {weeklyLog.routes.map((route) => (
                <g key={route.location}>
                  <motion.rect
                    initial={{ opacity: 0, scale: 0.8 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.5 }}
                    x={route.x - 45}
                    y={route.y - 45}
                    width="90"
                    height="90"
                    rx="8"
                    fill={getHeatColor(route.visits, maxVisits)}
                    fillOpacity={0.3 + (route.visits / maxVisits) * 0.5}
                    stroke={getHeatColor(route.visits, maxVisits)}
                    strokeWidth={hoveredRoute === route.location ? 3 : 1.5}
                    onMouseEnter={() => setHoveredRoute(route.location)}
                    onMouseLeave={() => setHoveredRoute(null)}
                    style={{ cursor: 'pointer' }}
                  />
                  <motion.circle
                    whileHover={{ scale: 1.3 }}
                    cx={route.x}
                    cy={route.y}
                    r={8 + route.visits}
                    fill={getHeatColor(route.visits, maxVisits)}
                    stroke="#F4E4BC"
                    strokeWidth="2"
                    onMouseEnter={() => setHoveredRoute(route.location)}
                    onMouseLeave={() => setHoveredRoute(null)}
                    style={{ cursor: 'pointer' }}
                  />
                  {hoveredRoute === route.location && (
                    <g>
                      <rect
                        x={route.x - 60}
                        y={route.y - 80}
                        width="120"
                        height="40"
                        rx="6"
                        fill="#0A2342"
                        stroke="#C9A227"
                        strokeWidth="2"
                      />
                      <text
                        x={route.x}
                        y={route.y - 62}
                        textAnchor="middle"
                        fill="#F4E4BC"
                        fontSize="12"
                        fontFamily="IM Fell English"
                      >
                        {route.location}
                      </text>
                      <text
                        x={route.x}
                        y={route.y - 48}
                        textAnchor="middle"
                        fill="#C9A227"
                        fontSize="11"
                      >
                        访问 {route.visits} 次
                      </text>
                    </g>
                  )}
                </g>
              ))}
              <text x="500" y="580" textAnchor="middle" fill="#C9A227" fillOpacity="0.5" fontSize="14">
                ⚓ 航线访问热度 ⚓
              </text>
            </svg>
            <div className="absolute bottom-3 left-3 flex items-center gap-2 bg-ocean-900/80 px-3 py-2 rounded border border-gold-500/30">
              <div className="flex gap-1">
                <div className="w-4 h-4 rounded" style={{ backgroundColor: '#3A7CA5' }} />
                <div className="w-4 h-4 rounded" style={{ backgroundColor: '#2A5A8C' }} />
                <div className="w-4 h-4 rounded" style={{ backgroundColor: '#1E5AA8' }} />
                <div className="w-4 h-4 rounded" style={{ backgroundColor: '#C9A227' }} />
              </div>
              <span className="text-parchment-300 text-xs">低 → 高</span>
            </div>
          </div>
        </motion.div>

        <motion.div variants={itemVariants} className="pirate-card p-6">
          <h2 className="heading-display text-xl text-gold-300 mb-4 flex items-center gap-2">
            <span>😊</span> 船员士气变化
          </h2>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={weeklyLog.crewMoraleHistory}>
                <defs>
                  <linearGradient id="moraleGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#C9A227" stopOpacity={0.4} />
                    <stop offset="95%" stopColor="#C9A227" stopOpacity={0} />
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(201, 162, 39, 0.15)" />
                <XAxis
                  dataKey="date"
                  stroke="#C9A227"
                  tick={{ fill: '#F4E4BC', fontSize: 11 }}
                  tickLine={{ stroke: '#C9A227' }}
                />
                <YAxis
                  domain={[0, 100]}
                  stroke="#C9A227"
                  tick={{ fill: '#F4E4BC', fontSize: 11 }}
                  tickLine={{ stroke: '#C9A227' }}
                />
                <Tooltip
                  contentStyle={{
                    backgroundColor: '#0A2342',
                    border: '2px solid #C9A227',
                    borderRadius: '8px',
                    fontFamily: 'IM Fell English',
                  }}
                  labelStyle={{ color: '#C9A227' }}
                  itemStyle={{ color: '#F4E4BC' }}
                />
                <Line
                  type="monotone"
                  dataKey="morale"
                  stroke="#C9A227"
                  strokeWidth={3}
                  dot={{ fill: '#C9A227', stroke: '#F4E4BC', strokeWidth: 2, r: 5 }}
                  activeDot={{ r: 8, fill: '#F4E4BC', stroke: '#C9A227', strokeWidth: 3 }}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </motion.div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <motion.div variants={itemVariants} className="pirate-card p-6">
          <h2 className="heading-display text-xl text-gold-300 mb-4 flex items-center gap-2">
            <span>🎯</span> 战斗统计雷达
          </h2>
          <div className="h-80">
            <ResponsiveContainer width="100%" height="100%">
              <RadarChart data={radarData}>
                <PolarGrid stroke="rgba(201, 162, 39, 0.2)" />
                <PolarAngleAxis
                  dataKey="dimension"
                  tick={{ fill: '#F4E4BC', fontSize: 12 }}
                />
                <PolarRadiusAxis
                  angle={30}
                  domain={[0, 100]}
                  tick={{ fill: '#C9A227', fontSize: 10 }}
                  stroke="rgba(201, 162, 39, 0.3)"
                />
                <Radar
                  name="本周数据"
                  dataKey="value"
                  stroke="#C9A227"
                  fill="#C9A227"
                  fillOpacity={0.4}
                  strokeWidth={2}
                />
                <Legend
                  wrapperStyle={{ fontFamily: 'IM Fell English' }}
                  formatter={(value) => <span style={{ color: '#F4E4BC' }}>{value}</span>}
                />
                <Tooltip
                  contentStyle={{
                    backgroundColor: '#0A2342',
                    border: '2px solid #C9A227',
                    borderRadius: '8px',
                    fontFamily: 'IM Fell English',
                  }}
                  itemStyle={{ color: '#F4E4BC' }}
                />
              </RadarChart>
            </ResponsiveContainer>
          </div>
        </motion.div>

        <motion.div variants={itemVariants} className="pirate-card p-6">
          <h2 className="heading-display text-xl text-gold-300 mb-4 flex items-center gap-2">
            <span>📅</span> 本周事件时间轴
          </h2>
          <div className="relative max-h-80 overflow-y-auto pr-2">
            <div className="absolute left-4 top-0 bottom-0 w-0.5 bg-gradient-to-b from-gold-500 via-gold-500/50 to-transparent" />
            <div className="space-y-4">
              {sortedEvents.length === 0 ? (
                <div className="text-center py-12 text-parchment-300">
                  <div className="text-5xl mb-3">🌊</div>
                  <p>本周风平浪静，暂无事件</p>
                </div>
              ) : (
                sortedEvents.map((event, idx) => {
                  const date = new Date(event.timestamp);
                  const timeStr = `${date.getMonth() + 1}/${date.getDate()} ${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`;
                  return (
                    <motion.div
                      key={event.id}
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: idx * 0.05 }}
                      className="relative pl-12"
                    >
                      <div className="absolute left-0 top-1 w-8 h-8 rounded-full bg-ocean-700 border-2 border-gold-500 flex items-center justify-center text-lg">
                        {getEventEmoji(event.type)}
                      </div>
                      <div className={`parchment-panel p-3 ${event.resolved ? 'opacity-70' : ''}`}>
                        <div className="flex items-start justify-between gap-2">
                          <div>
                            <h3 className="font-display font-bold text-ocean-700 text-sm">
                              {event.title}
                            </h3>
                            <p className="text-xs text-ocean-600 mt-1 line-clamp-2">
                              {event.description}
                            </p>
                          </div>
                          <span className="text-xs text-wood-700 whitespace-nowrap">
                            {timeStr}
                          </span>
                        </div>
                        {event.reward && (
                          <div className="mt-2 flex gap-2 flex-wrap">
                            {event.reward.gold && (
                              <span className="inline-flex items-center gap-1 bg-gold-500/30 text-ocean-700 px-2 py-0.5 rounded text-xs font-semibold">
                                💰 +{event.reward.gold}
                              </span>
                            )}
                            {event.reward.blueprints && event.reward.blueprints.length > 0 && (
                              <span className="inline-flex items-center gap-1 bg-copper-500/30 text-ocean-700 px-2 py-0.5 rounded text-xs font-semibold">
                                📋 +{event.reward.blueprints.length}
                              </span>
                            )}
                          </div>
                        )}
                        {event.penalty && (
                          <div className="mt-2 flex gap-2 flex-wrap">
                            {event.penalty.goldLoss && (
                              <span className="inline-flex items-center gap-1 bg-blood-400/30 text-ocean-700 px-2 py-0.5 rounded text-xs font-semibold">
                                💰 -{event.penalty.goldLoss}
                              </span>
                            )}
                            {event.penalty.crewLoss && (
                              <span className="inline-flex items-center gap-1 bg-blood-400/30 text-ocean-700 px-2 py-0.5 rounded text-xs font-semibold">
                                👥 -{event.penalty.crewLoss}
                              </span>
                            )}
                          </div>
                        )}
                      </div>
                    </motion.div>
                  );
                })
              )}
            </div>
          </div>
        </motion.div>
      </div>
    </motion.div>
  );
}
