import type {
  ShipHull,
  ShipCannon,
  ShipSail,
  ShipArmor,
  CrewMember,
  EnemyShip,
  TradeRecord,
  PlayerRank,
  MarketListing,
  VoyageEvent,
  WeeklyLog,
  Player,
  Weather,
} from './types';

export const SHIP_HULLS: ShipHull[] = [
  {
    id: 'hull-sloop',
    name: '单桅纵帆船',
    tier: 1,
    baseSpeed: 70,
    baseDefense: 20,
    maxCrew: 8,
    maxCannons: 4,
    cost: 500,
    description: '小型快速船只，适合侦察和突袭，火力较弱但机动性极佳。',
  },
  {
    id: 'hull-brig',
    name: '双桅横帆船',
    tier: 2,
    baseSpeed: 55,
    baseDefense: 40,
    maxCrew: 15,
    maxCannons: 8,
    cost: 1200,
    description: '平衡型战舰，速度与火力兼备，是海盗的标配选择。',
  },
  {
    id: 'hull-schooner',
    name: '多桅纵帆船',
    tier: 2,
    baseSpeed: 65,
    baseDefense: 30,
    maxCrew: 12,
    maxCannons: 6,
    cost: 1000,
    description: '近海航行的王者，浅水区机动性出色，适合贸易走私。',
  },
  {
    id: 'hull-frigate',
    name: '巡防舰',
    tier: 3,
    baseSpeed: 45,
    baseDefense: 65,
    maxCrew: 30,
    maxCannons: 16,
    cost: 3000,
    description: '中型战舰，火力与防护俱佳，可执行远洋任务。',
  },
  {
    id: 'hull-galleon',
    name: '西班牙大帆船',
    tier: 4,
    baseSpeed: 30,
    baseDefense: 85,
    maxCrew: 50,
    maxCannons: 24,
    cost: 6000,
    description: '重型远洋战舰，载重量巨大，是运送财宝的首选。',
  },
  {
    id: 'hull-man-o-war',
    name: '一级战列舰',
    tier: 5,
    baseSpeed: 20,
    baseDefense: 100,
    maxCrew: 80,
    maxCannons: 36,
    cost: 12000,
    description: '海上霸主，火炮甲板林立，唯有真正的大海盗才能驾驭。',
  },
];

export const SHIP_CANNONS: ShipCannon[] = [
  {
    id: 'cannon-6pdr',
    name: '6磅轻炮',
    tier: 1,
    damage: 8,
    fireRate: 2.5,
    range: 60,
    cost: 100,
    description: '轻型火炮，射速快但威力有限。',
  },
  {
    id: 'cannon-12pdr',
    name: '12磅加农炮',
    tier: 2,
    damage: 18,
    fireRate: 4,
    range: 80,
    cost: 300,
    description: '标准中型火炮，性价比之选。',
  },
  {
    id: 'cannon-18pdr',
    name: '18磅长管炮',
    tier: 3,
    damage: 30,
    fireRate: 5.5,
    range: 100,
    cost: 600,
    description: '射程和威力兼顾的远程火炮。',
  },
  {
    id: 'cannon-24pdr',
    name: '24磅重炮',
    tier: 3,
    damage: 45,
    fireRate: 7,
    range: 90,
    cost: 900,
    description: '重型火炮，近距离可击穿任何装甲。',
  },
  {
    id: 'cannon-32pdr',
    name: '32磅毁灭炮',
    tier: 4,
    damage: 65,
    fireRate: 9,
    range: 85,
    cost: 1500,
    description: '巨舰标配，一发足以撕裂船壳。',
  },
  {
    id: 'cannon-carronade',
    name: '短管卡隆炮',
    tier: 2,
    damage: 25,
    fireRate: 3,
    range: 40,
    cost: 400,
    description: '近战恶魔，近距离威力惊人但射程极短。',
  },
  {
    id: 'cannon-swivel',
    name: '回旋炮',
    tier: 1,
    damage: 5,
    fireRate: 1.5,
    range: 50,
    cost: 150,
    description: '专杀人员的轻型炮，对船员伤害极高。',
  },
  {
    id: 'cannon-mortar',
    name: '舰载迫击炮',
    tier: 4,
    damage: 80,
    fireRate: 15,
    range: 120,
    cost: 2000,
    description: '抛物线攻击，无视装甲直接造成毁灭性伤害。',
  },
];

export const SHIP_SAILS: ShipSail[] = [
  {
    id: 'sail-basic',
    name: '标准方帆',
    tier: 1,
    speedBonus: 0,
    maneuverBonus: 0,
    cost: 50,
    description: '最基础的帆装，无特殊加成。',
  },
  {
    id: 'sail-lateen',
    name: '三角拉丁帆',
    tier: 2,
    speedBonus: 8,
    maneuverBonus: 10,
    cost: 200,
    description: '逆风性能出色，大幅提升机动性。',
  },
  {
    id: 'sail-fore-and-aft',
    name: '纵帆装置',
    tier: 2,
    speedBonus: 12,
    maneuverBonus: 5,
    cost: 250,
    description: '顺风航行利器，显著提升航速。',
  },
  {
    id: 'sail-royal',
    name: '皇家全帆装',
    tier: 3,
    speedBonus: 20,
    maneuverBonus: 12,
    cost: 600,
    description: '多层帆装组合，各方面性能全面提升。',
  },
  {
    id: 'sail-junk',
    name: '中式硬帆',
    tier: 3,
    speedBonus: 15,
    maneuverBonus: 18,
    cost: 700,
    description: '来自东方的神秘帆装，机动性极佳。',
  },
];

export const SHIP_ARMORS: ShipArmor[] = [
  {
    id: 'armor-none',
    name: '无装甲',
    tier: 1,
    defenseBonus: 0,
    speedPenalty: 0,
    cost: 0,
    description: '裸奔的船体，最轻但最脆弱。',
  },
  {
    id: 'armor-oak',
    name: '橡木加固',
    tier: 2,
    defenseBonus: 15,
    speedPenalty: 3,
    cost: 300,
    description: '加厚橡木船壳，提供基础防护。',
  },
  {
    id: 'armor-double',
    name: '双层船壳',
    tier: 3,
    defenseBonus: 30,
    speedPenalty: 6,
    cost: 800,
    description: '双层交错船壳，抗弹性能大幅提升。',
  },
  {
    id: 'armor-copper',
    name: '铜皮包覆',
    tier: 3,
    defenseBonus: 25,
    speedPenalty: 2,
    cost: 1000,
    description: '船底铜皮防污防腐，速度损失极小。',
  },
  {
    id: 'armor-iron',
    name: '铁甲舰',
    tier: 4,
    defenseBonus: 55,
    speedPenalty: 10,
    cost: 2500,
    description: '铁板覆盖船体，近乎刀枪不入。',
  },
];

export const RECRUITABLE_CREW: CrewMember[] = [
  {
    id: 'crew-cap-1',
    name: '血腥杰克',
    role: 'captain',
    avatar: '🏴‍☠️',
    loyalty: 75,
    skills: { navigation: 85, leadership: 90, combat: 70 },
    level: 8,
    exp: 5200,
    contractPrice: 1500,
    description: '经验丰富的老海盗，曾在七大洋横行三十年。',
  },
  {
    id: 'crew-cap-2',
    name: '安妮·伯妮',
    role: 'captain',
    avatar: '⚓',
    loyalty: 88,
    skills: { navigation: 70, leadership: 95, combat: 85 },
    level: 6,
    exp: 3800,
    contractPrice: 1200,
    description: '勇猛无畏的女海盗，以领导能力闻名。',
  },
  {
    id: 'crew-cap-3',
    name: '黑胡子',
    role: 'captain',
    avatar: '💀',
    loyalty: 60,
    skills: { navigation: 95, leadership: 80, combat: 95 },
    level: 10,
    exp: 7800,
    contractPrice: 2500,
    description: '传说中的大海盗，嗜血残忍但战无不胜。',
  },
  {
    id: 'crew-cap-4',
    name: '航海家辛巴达',
    role: 'captain',
    avatar: '🧭',
    loyalty: 92,
    skills: { navigation: 99, leadership: 75, combat: 50 },
    level: 7,
    exp: 4500,
    contractPrice: 1800,
    description: '航行过世界每一片海域的传奇航海家。',
  },
  {
    id: 'crew-cap-5',
    name: '独脚希尔弗',
    role: 'captain',
    avatar: '🦜',
    loyalty: 45,
    skills: { navigation: 80, leadership: 85, combat: 75 },
    level: 9,
    exp: 6200,
    contractPrice: 2000,
    description: '狡猾的老海盗，忠诚需用金币衡量。',
  },
  {
    id: 'crew-gun-1',
    name: '铁腕汉斯',
    role: 'gunner',
    avatar: '💣',
    loyalty: 82,
    skills: { gunnery: 90, combat: 65 },
    level: 7,
    exp: 4100,
    contractPrice: 600,
    description: '百发百中的神炮手，能让炮弹长眼睛。',
  },
  {
    id: 'crew-gun-2',
    name: '火星麦克',
    role: 'gunner',
    avatar: '🔥',
    loyalty: 70,
    skills: { gunnery: 85, combat: 75 },
    level: 5,
    exp: 2800,
    contractPrice: 450,
    description: '热爱爆炸的疯狂炮手，射速惊人。',
  },
  {
    id: 'crew-gun-3',
    name: '沉默山姆',
    role: 'gunner',
    avatar: '🎯',
    loyalty: 90,
    skills: { gunnery: 95, combat: 50 },
    level: 8,
    exp: 5500,
    contractPrice: 800,
    description: '一言不发的精准射手，弹无虚发。',
  },
  {
    id: 'crew-gun-4',
    name: '火药皮特',
    role: 'gunner',
    avatar: '🧨',
    loyalty: 65,
    skills: { gunnery: 75, combat: 70 },
    level: 4,
    exp: 1800,
    contractPrice: 350,
    description: '年轻的火药专家，潜力巨大。',
  },
  {
    id: 'crew-gun-5',
    name: '独眼龙乔',
    role: 'gunner',
    avatar: '👁️',
    loyalty: 78,
    skills: { gunnery: 88, combat: 80 },
    level: 6,
    exp: 3500,
    contractPrice: 550,
    description: '失去一只眼后，另一只眼瞄准更准了。',
  },
  {
    id: 'crew-sail-1',
    name: '快腿乔尼',
    role: 'sailor',
    avatar: '⛵',
    loyalty: 85,
    skills: { sailing: 92, combat: 55 },
    level: 5,
    exp: 2900,
    contractPrice: 250,
    description: '攀爬绳索如履平地的敏捷水手。',
  },
  {
    id: 'crew-sail-2',
    name: '海中蛟龙',
    role: 'sailor',
    avatar: '🌊',
    loyalty: 80,
    skills: { sailing: 85, combat: 70 },
    level: 4,
    exp: 2000,
    contractPrice: 200,
    description: '在水里比在船上还自在的游泳健将。',
  },
  {
    id: 'crew-sail-3',
    name: '老汤姆',
    role: 'sailor',
    avatar: '🧓',
    loyalty: 95,
    skills: { sailing: 88, combat: 45 },
    level: 6,
    exp: 3600,
    contractPrice: 300,
    description: '服务过三代船长的忠诚老水手。',
  },
  {
    id: 'crew-sail-4',
    name: '大块头比尔',
    role: 'sailor',
    avatar: '💪',
    loyalty: 72,
    skills: { sailing: 70, combat: 88 },
    level: 5,
    exp: 2700,
    contractPrice: 280,
    description: '力大无穷的壮汉，近战好手。',
  },
  {
    id: 'crew-sail-5',
    name: '年轻的汤姆',
    role: 'sailor',
    avatar: '👦',
    loyalty: 98,
    skills: { sailing: 60, combat: 40 },
    level: 2,
    exp: 500,
    contractPrice: 100,
    description: '怀揣海盗梦想的新人小伙子。',
  },
];

export const ENEMY_SHIPS: EnemyShip[] = [
  {
    id: 'enemy-merchant-1',
    name: '肥美的商船',
    maxHp: 150,
    firepower: 20,
    defense: 15,
    speed: 35,
    crewCount: 10,
    loot: { gold: 800, blueprints: [] },
  },
  {
    id: 'enemy-sloop-1',
    name: '皇家侦察舰',
    maxHp: 120,
    firepower: 45,
    defense: 25,
    speed: 65,
    crewCount: 12,
    loot: { gold: 500, blueprints: ['bp-sloop'] },
  },
  {
    id: 'enemy-brig-1',
    name: '海盗黑珍珠号',
    maxHp: 280,
    firepower: 90,
    defense: 45,
    speed: 50,
    crewCount: 25,
    loot: { gold: 2500, blueprints: ['bp-brig', 'bp-12pdr'] },
  },
  {
    id: 'enemy-frigate-1',
    name: '英国皇家海军巡防舰',
    maxHp: 500,
    firepower: 180,
    defense: 70,
    speed: 40,
    crewCount: 50,
    loot: { gold: 6000, blueprints: ['bp-frigate', 'bp-18pdr'] },
  },
  {
    id: 'enemy-manowar-1',
    name: '无敌舰队旗舰',
    maxHp: 900,
    firepower: 320,
    defense: 95,
    speed: 18,
    crewCount: 120,
    loot: { gold: 15000, blueprints: ['bp-man-o-war', 'bp-32pdr', 'bp-iron'] },
  },
];

export const HISTORICAL_TRADES: TradeRecord[] = Array.from({ length: 20 }, (_, i) => ({
  id: `trade-hist-${i + 1}`,
  listingId: `listing-hist-${i + 1}`,
  buyerName: ['海盗王', '黑胡子二世', '安妮的复仇', '海上幽灵', '黄金骷髅'][i % 5],
  sellerName: ['深海猎手', '血腥玛丽', '加勒比之王', '风暴之子', '孤独的航海家'][i % 5],
  itemName: [
    'T2船体图纸',
    'T3火炮图纸',
    '精英炮手合同',
    '传奇船长合同',
    'T4装甲图纸',
  ][i % 5],
  price: [300, 800, 500, 1800, 1200, 400, 950, 600, 2200, 1500][i % 10] * (1 + (i % 3) * 0.1),
  timestamp: Date.now() - (i + 1) * 3600000 * 6,
  triggeredBounty: i % 7 === 0,
}));

export const MARKET_LISTINGS: MarketListing[] = [
  {
    id: 'listing-1',
    sellerId: 'npc-1',
    sellerName: '深海猎手',
    type: 'blueprint',
    item: { blueprintId: 'bp-frigate', blueprintName: '巡防舰图纸', blueprintTier: 3 },
    price: 1100,
    suggestedPriceMin: 900,
    suggestedPriceMax: 1300,
    listedAt: Date.now() - 7200000,
  },
  {
    id: 'listing-2',
    sellerId: 'npc-2',
    sellerName: '血腥玛丽',
    type: 'crewContract',
    item: {
      crew: RECRUITABLE_CREW[5],
    },
    price: 650,
    suggestedPriceMin: 500,
    suggestedPriceMax: 700,
    listedAt: Date.now() - 3600000,
  },
  {
    id: 'listing-3',
    sellerId: 'npc-3',
    sellerName: '加勒比之王',
    type: 'blueprint',
    item: { blueprintId: 'bp-32pdr', blueprintName: '32磅毁灭炮图纸', blueprintTier: 4 },
    price: 2400,
    suggestedPriceMin: 2000,
    suggestedPriceMax: 2800,
    listedAt: Date.now() - 1800000,
  },
  {
    id: 'listing-4',
    sellerId: 'npc-4',
    sellerName: '风暴之子',
    type: 'crewContract',
    item: {
      crew: RECRUITABLE_CREW[0],
    },
    price: 1700,
    suggestedPriceMin: 1400,
    suggestedPriceMax: 1800,
    listedAt: Date.now() - 900000,
  },
  {
    id: 'listing-5',
    sellerId: 'npc-5',
    sellerName: '孤独的航海家',
    type: 'blueprint',
    item: { blueprintId: 'bp-iron', blueprintName: '铁甲舰图纸', blueprintTier: 4 },
    price: 3000,
    suggestedPriceMin: 2500,
    suggestedPriceMax: 3500,
    listedAt: Date.now() - 300000,
  },
];

export const RANDOM_EVENTS: Omit<VoyageEvent, 'id' | 'timestamp' | 'resolved'>[] = [
  {
    type: 'treasure',
    title: '发现沉船宝藏！',
    description: '在海底发现了一艘古老沉船，里面装满了金币和珠宝！',
    reward: { gold: 1200, resources: { 丝绸: 5, 香料: 3 } },
  },
  {
    type: 'treasure',
    title: '漂流箱',
    description: '海面上漂来一个密封的木箱，里面有一张稀有图纸。',
    reward: { gold: 300, blueprints: ['bp-cannon-18pdr'] },
  },
  {
    type: 'enemy',
    title: '遭遇敌舰！',
    description: '一艘敌对海盗船从迷雾中冲出，战斗不可避免！',
  },
  {
    type: 'storm',
    title: '暴风雨来袭',
    description: '天空突然变暗，狂风巨浪拍打着船身，船只受到损伤。',
    penalty: { hpLoss: 40 },
  },
  {
    type: 'kraken',
    title: '海怪现身！',
    description: '巨大的触手从深海伸出，紧紧缠住了你的船！',
    penalty: { hpLoss: 80, crewLoss: 2 },
  },
  {
    type: 'island',
    title: '发现无名岛屿',
    description: '一座从未出现在海图上的小岛，上面可能藏有惊喜。',
    reward: { gold: 500, resources: { 木材: 10, 淡水: 8 } },
  },
  {
    type: 'merchant',
    title: '遇到商船',
    description: '一艘装满货物的商船正在缓慢航行，是抢夺还是交易？',
  },
  {
    type: 'storm',
    title: '飓风警报',
    description: '五节风速骤升为三十节，必须立即做出反应！',
    penalty: { hpLoss: 25, goldLoss: 100 },
  },
  {
    type: 'treasure',
    title: '海盗藏宝图',
    description: '在一只死海鸥的腿上绑着一张古老的藏宝图碎片。',
    reward: { gold: 800, blueprints: ['bp-sail-royal'] },
  },
  {
    type: 'enemy',
    title: '海军巡逻队',
    description: '皇家海军的巡逻舰发现了你！他们会将你绳之以法！',
  },
];

export const WEATHER_TYPES: Weather[] = [
  { type: 'clear', windSpeed: 8, windDirection: 45, visibility: 100 },
  { type: 'cloudy', windSpeed: 12, windDirection: 90, visibility: 85 },
  { type: 'rain', windSpeed: 20, windDirection: 180, visibility: 60 },
  { type: 'storm', windSpeed: 45, windDirection: 270, visibility: 25 },
  { type: 'fog', windSpeed: 5, windDirection: 0, visibility: 15 },
];

export const LEADERBOARD_DATA: {
  wealth: PlayerRank[];
  power: PlayerRank[];
  plunder: PlayerRank[];
} = {
  wealth: [
    { rank: 1, id: 'p1', name: '海盗王·摩根', avatar: '👑', value: 850000, level: 45 },
    { rank: 2, id: 'p2', name: '金牙夫人', avatar: '🦷', value: 620000, level: 38 },
    { rank: 3, id: 'p3', name: '深海领主', avatar: '🐙', value: 480000, level: 35 },
    { rank: 4, id: 'p4', name: '风暴追逐者', avatar: '🌀', value: 320000, level: 28 },
    { rank: 5, id: 'p5', name: '七海之王', avatar: '🌊', value: 290000, level: 26 },
    { rank: 6, id: 'p6', name: '加勒比幽灵', avatar: '👻', value: 210000, level: 22 },
    { rank: 7, id: 'p7', name: '独狼船长', avatar: '🐺', value: 180000, level: 20 },
    { rank: 8, id: 'p8', name: '红胡子', avatar: '🟥', value: 150000, level: 18 },
  ],
  power: [
    { rank: 1, id: 'p1', name: '海盗王·摩根', avatar: '👑', value: 9800, level: 45 },
    { rank: 2, id: 'p9', name: '铁舰队司令', avatar: '⚓', value: 8500, level: 40 },
    { rank: 3, id: 'p3', name: '深海领主', avatar: '🐙', value: 7200, level: 35 },
    { rank: 4, id: 'p10', name: '火炮大师', avatar: '💥', value: 6100, level: 30 },
    { rank: 5, id: 'p5', name: '七海之王', avatar: '🌊', value: 5400, level: 26 },
    { rank: 6, id: 'p11', name: '血斧船长', avatar: '🪓', value: 4200, level: 23 },
    { rank: 7, id: 'p4', name: '风暴追逐者', avatar: '🌀', value: 3800, level: 28 },
    { rank: 8, id: 'p7', name: '独狼船长', avatar: '🐺', value: 3100, level: 20 },
  ],
  plunder: [
    { rank: 1, id: 'p12', name: '掠夺大师', avatar: '💰', value: 342, level: 42 },
    { rank: 2, id: 'p1', name: '海盗王·摩根', avatar: '👑', value: 289, level: 45 },
    { rank: 3, id: 'p13', name: '商船克星', avatar: '🏴‍☠️', value: 245, level: 36 },
    { rank: 4, id: 'p2', name: '金牙夫人', avatar: '🦷', value: 198, level: 38 },
    { rank: 5, id: 'p14', name: '海岸线猎手', avatar: '🏝️', value: 176, level: 31 },
    { rank: 6, id: 'p3', name: '深海领主', avatar: '🐙', value: 152, level: 35 },
    { rank: 7, id: 'p15', name: '骷髅旗', avatar: '💀', value: 134, level: 27 },
    { rank: 8, id: 'p6', name: '加勒比幽灵', avatar: '👻', value: 112, level: 22 },
  ],
};

export const INITIAL_PLAYER: Player = {
  id: 'player-1',
  name: '初出茅庐的海盗',
  avatar: '🏴‍☠️',
  gold: 5000,
  level: 1,
  reputation: 100,
  ships: [],
  activeShipId: '',
  crew: [],
  inventory: {
    blueprints: [
      { id: 'bp-sloop', name: '单桅纵帆船图纸', tier: 1 },
      { id: 'bp-6pdr', name: '6磅轻炮图纸', tier: 1 },
    ],
    resources: {
      木材: 20,
      淡水: 15,
      食物: 10,
    },
  },
  stats: {
    totalWealth: 5000,
    totalBattles: 0,
    shipsSunk: 0,
    plunderCount: 0,
  },
};

export const INITIAL_WEEKLY_LOG: WeeklyLog = {
  weekStart: new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0],
  weekEnd: new Date().toISOString().split('T')[0],
  voyageCount: 8,
  battleWins: 5,
  battleLosses: 2,
  totalGoldEarned: 12500,
  totalGoldSpent: 4200,
  routes: [
    { location: '加勒比海', visits: 12, x: 220, y: 350 },
    { location: '直布罗陀海峡', visits: 8, x: 480, y: 280 },
    { location: '马达加斯加', visits: 5, x: 720, y: 480 },
    { location: '南中国海', visits: 3, x: 860, y: 320 },
    { location: '冰岛附近', visits: 2, x: 420, y: 100 },
  ],
  crewMoraleHistory: Array.from({ length: 7 }, (_, i) => ({
    date: new Date(Date.now() - (6 - i) * 86400000).toISOString().split('T')[0],
    morale: 60 + Math.floor(Math.random() * 35),
  })),
  battleStats: {
    shipsSunk: 7,
    cannonsFired: 234,
    damageDealt: 4200,
    damageTaken: 1800,
    crewLost: 3,
    crewRecruited: 5,
  },
  events: [],
};
